### ISSUE TITLE
Remove standard click tracker

### ISSUE THREAD

**Issue by deeps96** [HPI-BP2017N2/URLCleaner#1]
I WANT TO remove standard click tracker
IN ORDER TO not generate trackable clicks to idealo customers.

Acceptance criteria:

- [x] The URLCleaner offers a GET-route '/clean' and consumes a parameter called url
- [x] The URLCleaner removes all click trackers, specified in a config.
- [x] The URLCleaner returnes the cleaned url.

**Comment by deeps96** [comment]
Tasks:

- [x] Setup the basic Spring Environment
- [x] Configure travis

**Comment by deeps96** [comment]
[tracker-list.txt](https://github.com/HPI-BP2017N2/URLCleaner/files/1875081/tracker-list.txt)
